### ISSUE TITLE
HttpServletRequest2.doGetSession()何时调用的？

### ISSUE THREAD

**Issue by hooverhe** [ihaolin/session#1]
大神，HttpServletRequest2.doGetSession()何时调用的？

**Comment by ihaolin** [comment]
后续业务代码的`request.getSession()`会最终调用到这里。

**Comment by hooverhe** [comment]
Users中的业务注释了，还是可以调用，我找了好久直接调用的地方没有找到。我记得以前必须显示调用request.getSession()才可以访问Session，但在你的代码中看不到哪里调用了。

**Comment by hooverhe** [comment]
<dependency>
            <groupId>me.hao0</groupId>
            <artifactId>common</artifactId>
            <version>1.1.0</version>
        </dependency>  这个common是从哪个仓库下载下来的？

**Comment by ihaolin** [comment]
maven中心仓库

**Comment by hooverhe** [comment]
maven中心仓库怎么会有你私有的包啊

**Comment by ihaolin** [comment]
自己发布啊
